//load the patients.csv file
var fs = require('fs');
const csv = require('csv-parser');
var mkFhir = require('fhir.js');

const readCSV = async () => {
    const results = [];
    return new Promise((resolve, reject) => {
        fs.createReadStream('patients.csv')
            .pipe(csv())
            .on('data', (data) => results.push(data))
            .on('end', () => {resolve(results);});
    });
}

//create a FHIR patient resource from the json patient, need to check generated
function createFhirPatient(jsonPatient){
    const patient = {
        "resourceType": "Patient",
        "id": jsonPatient.id,
        "meta": {
            "profile": [ "http://hl7.org/fhir/us/core/StructureDefinition/us-core-patient" ]
        },
        "text": {
            "status": "generated",
            "div": "<div xmlns=\"http://www.w3.org/1999/xhtml\">Generated by fedevale</div>"
        },
        "active": true,
        "name": [
            {
                "use": "official",
                "text": jsonPatient.first + " " + jsonPatient.last,
                "family": jsonPatient.last,
                "given": [
                    jsonPatient.first
                ],
                "prefix": [
                    jsonPatient.prefix
                ],
                "suffix": [
                    jsonPatient.suffix
                ],
                "period": {
                    "start": jsonPatient.birthDate,
                    "end": jsonPatient.deathDate
                }
            }
        ],

    };

    return patient;
}




//create a FHIR client
var client = mkFhir({
    baseUrl: 'http://hapi.fhir.org/baseR4'
});

client
    .search( {type: 'Patient', query: { 'birthdate': '1974' }})
    .then(function(res){
        var bundle = res.data;
        var count = (bundle.entry && bundle.entry.length) || 0;
        console.log("# Patients born in 1974: ", count);
    })
    .catch(function(res){
        //Error responses
        if (res.status){
            console.log('Error', res.status);
        }

        //Errors
        if (res.message){
            console.log('Error', res.message);
        }
    });


readCSV().then((data) => {
    var pat1 = createFhirPatient(data[0]);
    console.log(pat1);

    //create a FHIR patient resource from the json patient, need to check generated
    client.create(pat1, 
        function(entry){
            console.log(entry.id)
            console.log("success")
         },
         function(error){
           console.error(error)
           console.log("error")
         }    
    )
});